facebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path
# 현재폴더(urls.py가 있는 폴더)->posts에 있는 views.py의 파일을 가지고와서 
# 그 안에 list를 실행
from . import views
# app_name => 앱이 여러개로 분리되는 것을 대비해서 적어줌.
app_name = 'posts'

urlpatterns = [
    # name => 변수 안에 이름을 정해줘서 나중에 바꾸게 쉽게끔
    path('', views.list, name="list"),
    path('create/', views.create, name="create"),
    path('<int:id>/delete', views.delete, name="delete"),
    path('<int:id>/update', views.update, name="update"),
    path('<int:id>/comment_new', views.comment_new, name="comment_new"),
    path('<int:id>/comment/<int:comment_id>/delete', views.comment_delete, name="comment_delete"),
    ]

posts/models.py
from django.db import models

# Create your models here.
class Facebook(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    
class Comment(models.Model):
    comment = models.CharField(max_length=100)
    facebook = models.ForeignKey(Facebook, on_delete=models.CASCADE)

posts/forms.py
from django import forms
# 현재 경로의 models에서 모델을 가져옴
from .models import Facebook, Comment

# Model Form (모델 폼)
class FacebookForm(forms.ModelForm):
	class Meta:
		model = Facebook
		fields = '__all__'
# 		fields = ['title', 'content'] # '__all__' 설정시 전체 필드 추가

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment',]
		

posts/views.py
from django.shortcuts import render, redirect
from .forms import FacebookForm, CommentForm
from .models import Facebook, Comment

# Create your views here.
def list(request):
    posts = Facebook.objects.all()
    comment_form = CommentForm()
    return render(request, 'posts/list.html', {"posts":posts, "comment_form":comment_form})
    
def create(request):
    if request.method == "POST":
        form = FacebookForm(request.POST)
        if form.is_valid():
            form.save()
            # 서버 최상단의 posts로 가려면 /posts/ 앞에 / 필요
            return redirect("/posts/")
    else:
        form = FacebookForm()
        # form.save()
        return render(request, 'posts/create.html', {"form":form})

def delete(request, id):
    post = Facebook.objects.get(id=id)
    post.delete()
    return redirect("posts:list")

def update(request, id):
    post = Facebook.objects.get(id=id)
    if request.method == "POST":
        form = FacebookForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect("posts:list")
        
    else:
        # 인스턴스라는 항목에 넣어주기 위해
        form = FacebookForm(instance=post)
        return render(request, 'posts/update.html', {"form":form})
    # form.save()
    
def comment_new(request,id): # 사실 POST방식은 필요하지 않습니다,,
    # 어디에 속해있는 정보를 달기
    facebook = Facebook.objects.get(id=id)
    if request.method == 'POST':
        # 여기서 commentForm이 하는 일은?
        # 사용자가 입력 할 수 있도록 만들어줌 + (데이터를 입력하면) 입력한 데이터를 받아야됨.
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # 정보를 저장해야되는데 그 전에 id값도 필요하니까 잠시 멈춰봐!
            comment = comment_form.save(commit=False)
            # 어떤 게시물에 속해있는지에 대한 정보가 fb이 가지고있음.
            comment.facebook = facebook
            comment.save()
            return redirect('posts:list')
            # 위와 같은 문장이지만, 또 posts를 모두 가져와야되는 코드+가 필요
            # return render(request, "posts/list.html",{'posts':posts})
            
def comment_delete(request, id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return redirect('posts:list')

posts/templates/posts/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <!--사용자가 submit 버튼을 눌렀을때 데이터를 가져와서 /posts/create/에 넣어줌.-->
    <form action="/posts/create/" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="제출"/>
    </form>
</body>
</html>

posts/templates/posts/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>여기는 리스트</h1>
    <div>
    {% for post in posts %}
        <h1>{{post.title}}</h1>
        <h3>{{post.content}}</h3>
        <a href="{% url "posts:delete" post.id %}">삭제</a>
        <a href="{% url "posts:update" post.id %}">수정</a>
        <form method='post' action="{% url 'posts:comment_new' post.id %}">
            <!--post방식이기 때문-->
            {% csrf_token %}
            {{comment_form}}
            <input type="submit" value="Submit"/>
        </form>
        {% for comment in post.comment_set.all %}
            <p>{{comment.comment}}</p>
            <!--<p>{{comment.content}} 나중에 변수정할때 주의</p>--> 
            <a href="{% url 'posts:comment_delete' post.id comment.id %}">삭제</a>
        {% endfor %}
    {% endfor %}
    </div>
</body>
</html>

posts/templates/posts/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <!--<form action="(비우면 현재의 위치로 전송)" method="post">-->
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="제출"/>
    </form>
</body>
</html>